apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: my-app-namespace
data:
  application.properties: |-
    spring.mvc.hiddenmethod.filter.enabled=true
    spring.datasource.url=jdbc:postgresql://my-project-server.postgres.database.azure.com/postgres
    spring.datasource.username=postgres
    spring.datasource.password=EscanorSama123
    spring.datasource.hikari.connection-timeout=20000
    spring.datasource.hikari.maximum-pool-size=5
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
