apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: my-app-namespace
spec:
  clusterIP: None
  ports:
    - name: database
      port: 5432
      protocol: TCP
  selector:
    app: database