apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: my-app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
